// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgFUsIRTdane6vj_7bIFdQsPIRcz70dQY',
    appId: '1:998928447620:web:d7eecac439c48eb0202ad1',
    messagingSenderId: '998928447620',
    projectId: 'echo-lens',
    authDomain: 'echo-lens.firebaseapp.com',
    storageBucket: 'echo-lens.appspot.com',
    measurementId: 'G-5QX7PL641E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4DR501X11d9iPb230fYgH6RxwhQxlqGY',
    appId: '1:998928447620:android:ee6d54d5da1f8c7a202ad1',
    messagingSenderId: '998928447620',
    projectId: 'echo-lens',
    storageBucket: 'echo-lens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT6u-iMGnaqBu76xYwCEy0qazgm5v6WrY',
    appId: '1:998928447620:ios:dfddeaa1617317ea202ad1',
    messagingSenderId: '998928447620',
    projectId: 'echo-lens',
    storageBucket: 'echo-lens.appspot.com',
    androidClientId: '998928447620-ckkk2mubfc7s6m0q0kk2ctaoml9f0fb1.apps.googleusercontent.com',
    iosClientId: '998928447620-p83nbr9pv7ilsqspo6s0mcgqvmhabqp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT6u-iMGnaqBu76xYwCEy0qazgm5v6WrY',
    appId: '1:998928447620:ios:dfddeaa1617317ea202ad1',
    messagingSenderId: '998928447620',
    projectId: 'echo-lens',
    storageBucket: 'echo-lens.appspot.com',
    androidClientId: '998928447620-ckkk2mubfc7s6m0q0kk2ctaoml9f0fb1.apps.googleusercontent.com',
    iosClientId: '998928447620-p83nbr9pv7ilsqspo6s0mcgqvmhabqp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgFUsIRTdane6vj_7bIFdQsPIRcz70dQY',
    appId: '1:998928447620:web:af9298cc9750e36e202ad1',
    messagingSenderId: '998928447620',
    projectId: 'echo-lens',
    authDomain: 'echo-lens.firebaseapp.com',
    storageBucket: 'echo-lens.appspot.com',
    measurementId: 'G-00HLRL2HSV',
  );
}
